Add name and location query
MycroftAI/skill-configuration pull request #12
Opened 2017-12-10 05:21 UTC by penrods

This add the ability to ask the name and the location settings
for the device.  Also switches to the Apache 2.0 license and
updates the README with more info.

2017-12-10 06:28 UTC, MatthewScholefield commented
This will fail on older devices without intent decorators or the configuration change. If breaking compatibility is intended, then make sure to also remove the unnecessary try catch in precise methods, and add the intent decorators to the other handlers.

2017-12-10 07:24 UTC, penrods commented
We added intent_hander() 10 months ago.  If they still haven't updated, then they need to.  :)

We officially support 17.08 and forward, which is 0.9+.  The localConf  was introduced 3 months ago, so that is outside the 0.9+ window, but since some of the early shipping units predated this (June-ish) it is probably worth keeping the backwards compatibility.

2017-12-10 08:12 UTC, MatthewScholefield commented
That's fine. If that's what we are deciding to support, all I see that needs to be changed is:
 - Change remaining handlers to decorator
 - Import legacy `ConfigurationManager` instead of `Configuration`
 - Remove try catch on handle_update_precise and handle_get_listener (since `ConfigurationManager.get()` is always safe to use)

2017-12-11 15:36 UTC, penrods commented
Ping

2017-12-11 18:41 UTC, MatthewScholefield requested changes
Looks good. Just a small typo to fix.

2017-12-11 18:41 UTC, MatthewScholefield commented on __init__.py
> +        self.where_are_you(message)
```python
self.handle_where_are_you
```

2017-12-11 19:24 UTC, MatthewScholefield approved these changes

2017-12-11 19:27 UTC, merged