Fix config setting bug and add ability to get listener
MycroftAI/skill-configuration pull request #8
Opened 2017-11-15 23:05 UTC by MatthewScholefield

Previously, the config assignment was bypassed when the code returned early to speak to the user that the download has started.

This also allows for phrases like `what is the current listener`.

2017-11-15 23:52 UTC, penrods requested changes
Couple minor things, then good to go.

2017-11-15 23:52 UTC, penrods commented on vocab/en-us/GetKeyword.voc
> +whats
normalize() takes care of this, transforming "what's" and "whats" into "what is"

2017-11-15 23:52 UTC, penrods commented on vocab/en-us/GetKeyword.voc
> +show me
"Show" is an odd word here.  In the future (18.02) we will be using "show me" to indicate things that will be sent to an associated screen.  If you would intend this to show something, then I'm fine leaving this.

We should allow "tell me"

2017-11-16 00:03 UTC, MatthewScholefield commented
OK, I've amended the commit.

On Wed, Nov 15, 2017, 5:52 PM Steve Penrod <notifications@github.com> wrote:

> *@penrods* requested changes on this pull request.
>
> Couple minor things, then good to go.
> ------------------------------
>
> In vocab/en-us/GetKeyword.voc
> <https://github.com/MycroftAI/skill-configuration/pull/8#discussion_r151286633>
> :
>
> > @@ -0,0 +1,4 @@
> +whats
>
> normalize() takes care of this, transforming "what's" and "whats" into
> "what is"
> ------------------------------
>
> In vocab/en-us/GetKeyword.voc
> <https://github.com/MycroftAI/skill-configuration/pull/8#discussion_r151286982>
> :
>
> > @@ -0,0 +1,4 @@
> +whats
> +what is
> +give me
> +show me
>
> "Show" is an odd word here. In the future (18.02) we will be using "show
> me" to indicate things that will be sent to an associated screen. If you
> would intend this to show something, then I'm fine leaving this.
>
> We should allow "tell me"
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MycroftAI/skill-configuration/pull/8#pullrequestreview-76970570>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFmlS6h8rLuTJoESbx-NOHzoYm0vBoUWks5s23kqgaJpZM4Qftfd>
> .
>

2017-11-16 00:14 UTC, penrods approved these changes
LGTM

2017-11-16 00:14 UTC, merged